# Generated by Django 2.0.5 on 2018-10-25 12:19

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_student', models.BooleanField(default=False)),
                ('is_faculty', models.BooleanField(default=False)),
                ('is_office', models.BooleanField(default=False)),
                ('is_dppc', models.BooleanField(default=False)),
                ('is_hod', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplyLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveFrom', models.DateField()),
                ('LeaveTo', models.DateField()),
                ('TypeOfLeave', models.CharField(choices=[('Ordinary', 'Ordinary'), ('Medical', 'Medical'), ('Acedemic', 'Acedemic'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity')], default='', max_length=255)),
                ('ReasonForLeave', models.CharField(max_length=200)),
                ('Doc1', models.FileField(blank=True, null=True, upload_to='documents')),
                ('Doc2', models.FileField(blank=True, null=True, upload_to='documents')),
                ('AddressWhileOnLeave', models.CharField(max_length=200)),
                ('PhoneNumberWhileOnLeave', models.CharField(max_length=20)),
                ('DateOfApply', models.DateField(default=datetime.datetime.now)),
                ('Flag', models.IntegerField(default=0)),
                ('SentTo', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Supervisor'), ('2', 'TAinstructor'), ('3', 'DPPC')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Remark', models.CharField(max_length=200)),
                ('Person', models.CharField(max_length=40)),
                ('DateOfComment', models.DateField(default=datetime.datetime.now)),
                ('Leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leave_portal.ApplyLeave')),
            ],
        ),
        migrations.CreateModel(
            name='Dppc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default=' ', null=True, upload_to='faculty')),
                ('webmail', models.CharField(max_length=128)),
                ('mob_num', models.CharField(max_length=128)),
                ('dppc_id', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dpppc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default=' ', null=True, upload_to='faculty')),
                ('webmail', models.CharField(max_length=128)),
                ('mob_num', models.CharField(max_length=128)),
                ('faculty_id', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default=' ', null=True, upload_to='faculty')),
                ('webmail', models.CharField(max_length=128)),
                ('mob_num', models.CharField(max_length=128)),
                ('hod_id', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hod', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, default=' ', null=True, upload_to='faculty')),
                ('webmail', models.CharField(max_length=128)),
                ('mob_num', models.CharField(max_length=128)),
                ('staff_id', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='student')),
                ('roll_no', models.CharField(default=' ', max_length=128, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('webmail', models.CharField(max_length=128, unique=True)),
                ('course', models.CharField(blank=True, choices=[('Mtech', 'Mtech'), ('Phd', 'Phd'), ('NA', 'NA')], max_length=128)),
                ('acedemic_year', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=0)),
                ('present_semester', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True)),
                ('hostel_name', models.CharField(blank=True, choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('Married_Scholar', 'Married_Scholar'), ('NA', 'NA')], default='', max_length=255)),
                ('room_number', models.CharField(blank=True, default='', max_length=10)),
                ('mob_number', models.CharField(default=' ', max_length=15)),
                ('emergency_mob_num', models.CharField(blank=True, default=' ', max_length=15)),
                ('TA_instructor', models.CharField(blank=True, default='', max_length=200)),
                ('Supervisor_1', models.CharField(blank=True, default='', max_length=200)),
                ('Ordinary', models.IntegerField(default=15)),
                ('Medical', models.IntegerField(default=15)),
                ('Acedemic', models.IntegerField(default=30)),
                ('Maternity', models.IntegerField(default=135)),
                ('Paternity', models.IntegerField(default=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
        migrations.AddField(
            model_name='applyleave',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applyleaves', to='leave_portal.Student'),
        ),
    ]
