# Generated by Django 2.1.3 on 2018-11-05 11:26

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leave_portal', '0003_auto_20181104_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyleave',
            name='SentTo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('2', 'Supervisor'), ('1', 'TAinstructor')], max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='acedemic_year',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='present_semester',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], default=1, null=True),
        ),
    ]
